[workspace]
authors = ["softwareentrepreneer <softwareentrepreneer+pfund@gmail.com>"]
channels = ["conda-forge"]
name = "pfund"
# NOTE: if encounter bug in pixi when running "pixi lock", remove pixi.lock, then set platforms = ["osx-arm64"] first
# then manually add back other platforms
platforms = ["osx-arm64", "linux-64"]
version = "0.0.2"

[tasks]


[tasks.test-all]
depends-on = [
  { task = "test", environment = "py311" },
  { task = "test", environment = "py312" },
  { task = "test", environment = "py313" },
  # { task = "test", environment = "py314" },
]

[dependencies]
python = ">=3.11"
uv = ">=0.8.17"

[pypi-dependencies]
pfeed = ">=0.0.5"
pfolio = ">=0.0.2"
mtflow = ">=0.0.1.dev2"
rich = ">=13.9.4"
click = ">=8.1.8"
trogon = ">=0.6.0"
platformdirs = ">=4.3.8"
python-dotenv = ">=1.1.1"
pyyaml = ">=6.0.2"
httpx = ">=0.28.1"
websockets = ">=15.0.1"
scikit-learn = ">=1.7.2"
numba = ">=0.61.2"
pfund-ibapi = ">=10.39.1"

[environments]
dev = ["py311", "dev", "editable", "optional"]
py311 = ["py311", "test", "editable", "optional"]
py312 = ["py312", "test", "editable", "optional"]
py313 = ["py313", "test", "editable", "optional"]
# py314 = ["py314", "test", "editable", "optional"]

[feature.optional.pypi-dependencies]
ta-lib = ">=0.6.7"
pfund-plot = { version = ">=0.0.1.dev2", extras = ["jupyter"] }

[feature.optional.dependencies]
libta-lib = ">=0.6.4"

[feature.editable.pypi-dependencies]
pfeed = { path = "../pfeed", editable = true }
pfolio = { path = "../pfolio", editable = true }
pfund-plot = { path = "../pfund-plot", editable = true }
mtflow = { path = "../mtflow", editable = true }

[feature.dev.pypi-dependencies]
pybit = ">=5.11.0"
torch = ">=2.8.0"
ruff = ">=0.13.0"
pre-commit = ">=4.3.0"
commitizen = ">=4.9.1"
python-semantic-release = ">=10.4.0"
pdoc = ">=15.0.4"
[feature.dev.tasks]
precommit = "pre-commit run --all-files"
lint = "ruff check ."
lint-fix = "ruff check --fix ."
fmt = "ruff format ."
typecheck = "uvx ty check"

[feature.dev.dependencies]
mystmd = ">=1.6.1"

[feature.test.pypi-dependencies]
pytest = ">=8.4.2"
pytest-cov = ">=7.0.0"
pytest-mock = ">=3.15.0"
pytest-xdist = ">=3.8.0"
pytest-asyncio = ">=1.1.0"
pytest-recording = ">=0.13.4"
testcontainers = ">=4.13.0"
[feature.test.tasks]
test = "pytest"
test-new = "pytest --record-mode=all"  # record new interactions, useful to update recordings in case data formats returned have changed
test-ci = "pytest --record-mode=none"  # fail a test if no recording is found

[feature.py311.dependencies]
python = "3.11.*"

[feature.py312.dependencies]
python = "3.12.*"

[feature.py313.dependencies]
python = "3.13.*"

# [feature.py314.dependencies]
# python = "3.14.*"
